### PR TITLE
Upgrade to use react-transform-hmr, webpack-hot-middleware and webpack-dev-middleware

### LINKED ISSUE #27: Replace deprecated react-hot-loader module
[react-hot-loader is deprecated](https://github.com/gaearon/react-hot-loader#deprecation-notice). Once the migration guide is posted, let's migrate to the new suite of tools.

### PR DESCRIPTION
**Pull request by kevinold**
Fixes #27

### CODE REVIEW

**Comment by banderson** [comment]
@kevinold on fire :fire: :fire: :fire: 

Did you follow a guid to do this or have you done this before? I'll give this a test run later on and merge if it's all good. Thanks man!

**Comment by kevinold** [comment]
@banderson No guide, but it's all derived from the boilerplate that is linked from the react-transform-hmr repo (https://github.com/gaearon/react-transform-boilerplate) and getting this setup in my day to day environment for several repos.  I decided to bite the bullet early on and make the migration from react-hot-loader and I'm glad I did.  This version feels more solid.

**Comment by kevinold** [comment]
@banderson Going to merge this?

**Comment by banderson** [comment]
:+1:

**Pull request merged**
